apiVersion: v1
kind: Pod
metadata:
  name: cc-pub-mts
  labels:
    purpose: demonstrate-cc-pub-mts
spec:
  containers:
    - name: cc-pub-mts-container
      image: huangfulibo/cc-pub-multitopics:0.0.1
  restartPolicy: OnFailure
---
apiVersion: v1
kind: Pod
metadata:
  name: cc-sub-mts
  labels:
    purpose: demonstrate-cc-sub-mts
spec:
  containers:
    - name: cc-sub-mts-container
      image: huangfulibo/cc-sub-multitopics:0.0.1
  restartPolicy: OnFailure

